name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - '**.bicep'
      - '.github/workflows/deploy-infra.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KEY_VAULT_NAME: leonardo-kv-2024
      KEY_VAULT_SECRET_NAME_ACR_USERNAME: acr-admin-username
      KEY_VAULT_SECRET_NAME_ACR_PASSWORD: acr-admin-password
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get docker registry credentials from Azure Key Vault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "REGISTRY_USERNAME=$(az keyvault secret show --name ${{ env.KEY_VAULT_SECRET_NAME_ACR_USERNAME }} --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV
          echo "REGISTRY_PASSWORD=$(az keyvault secret show --name ${{ env.KEY_VAULT_SECRET_NAME_ACR_PASSWORD }} --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV
    
    - name: Deploy Bicep
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: 'e0b9cada-61bc-4b5a-bd7a-52c606726b3b'
        resourceGroupName: 'BCSAI2024-DEVOPS-STUDENTS-A-DEV'
        template: ./main.bicep
        parameters: ./main.parameters.json
        deploymentName: 'github-workflow-${{ github.run_number }}'